---
title: "pkgproject package and shiny app vignette"
author: "Daniel Szenes, Özgür Aydemir, Louis Del Perugia, Francesco Darino, Sophie La Gennusa "
       
        
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Data processing

```{r}
library(tidyverse)
library(knitr)
library(ggplot2)
library(ggrepel)
data <- readxl::read_excel("~/UNIL 2021/Programming_tools/project--G4/scripts/nasty.xlsx")


data$Measure1 <- as.double(data$Measure1)
data$Measure2 <- as.double(data$Measure2)
data$Measure3 <- as.double(data$Measure3)
data$Measure4 <- as.double(data$Measure4)
data$Measure5 <- as.double(data$Measure5)
data$Measure6 <- as.double(data$Measure6)
data$Tare <- as.double(data$Tare)
data$Target.Value <- as.double(data$Target.Value)
data_try<- data
```



# summary_stat
illustrate the funtion

```{r}

library(pkgproject)
summary_stat(data_try,929)
```

# request_CL

```{r}
request_CL(data_try,929)
```

```{r}
R_bar_chart(data,254)
```




